### ISSUE TITLE
Building the project generates errors

### ISSUE THREAD

**Issue by skneife** [jurebajt/coffee-election-ng-app-example#1]
Hi,

I have used the following command line to get started: 
1) npm install
2) ng build.

For the 2nd I got the followings errors:
_ERROR in ./src/styles.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'_

Have you an idea to solved it?
Thanks

Sam

**Comment by georgebyte** [comment]
Hi,

it seems node-sass 4.9.3 doesn't support Node version > 11 (https://github.com/sass/node-sass#node-version-support-policy). As a workaround, try building the project with Node version 10.

Best,
George
